version: "3.7"

services:
  api:
    build: . # Only for now, delete this when building with gitlab's CI/CD
    image: registry.gitlab.com/steffbeckers/strapi
    environment:
      - NODE_ENV=development
      - HOST=strapi.steffbeckers.eu
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GBt4teCCcZ5QYYkScfMn
    volumes:
      - /root/strapi/mongodb:/data/db
      - /root/strapi/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
