version: '3.7'

services:
  api:
    build: .
    image: strapi/strapi
    networks:
      - reverse-proxy_default
      - default
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    volumes:
      - /root/strapi/app:/usr/src/api/strapi-app
    depends_on:
      - db
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    networks:
      - default
    volumes:
      - /root/strapi/mongodb:/data/db
  ssh:
    image: corbinu/ssh-server
    networks:
      - default
    volumes:
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro

networks:
  reverse-proxy_default:
    external: true
  default:
    internal: true
