version: "3.7"

services:
  api:
    image: registry.gitlab.com/steffbeckers/strapi
    environment:
      - NODE_ENV=test
      - HOST=strapi.steffbeckers.eu
    networks:
      - reverse-proxy_default
      - default
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    volumes:
      - /root/strapi-test/mongodb:/data/db
      - /root/strapi-test/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default
  ssh:
    image: corbinu/ssh-server
    volumes:
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
    networks:
      - default

networks:
  reverse-proxy_default:
    external: true
  default:
    internal: true
