version: "3.7"

services:
  api:
    build: . # Only for now, delete this when building with gitlab's CI/CD
    image: registry.gitlab.com/steffbeckers/strapi
    environment:
      - NODE_ENV=production
      - HOST=strapi.steffbeckers.eu
    networks:
      # - reverse-proxy_default
      - default
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GBt4teCCcZ5QYYkScfMn
    volumes:
      - /root/strapi/mongodb:/data/db
      - /root/strapi/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default
  mongodb-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=strapi
      - ME_CONFIG_MONGODB_AUTH_USERNAME=strapi
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=SfqWXWQFJXy55G6VDSaE
    networks:
      - default
  ssh:
    image: corbinu/ssh-server
    volumes:
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
    networks:
      - default

networks:
  # reverse-proxy_default:
  #   external: true
  default:
    internal: true
