version: "3.7"

services:
  api:
    build: .
    image: registry.gitlab.com/steffbeckers/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=SfqWXWQFJXy55G6VDSaE
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost:1337
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GBt4teCCcZ5QYYkScfMn
    ports:
      - "27017:27017"
    volumes:
      - C:\Docker\volumes\strapi\mongodb:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongodb-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=strapi
      - ME_CONFIG_MONGODB_AUTH_USERNAME=strapi
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=SfqWXWQFJXy55G6VDSaE
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
