version: "3.7"

services:
  api:
    build: . # Only for now, delete this when building with gitlab's CI/CD
    image: registry.gitlab.com/steffbeckers/strapi
    environment:
      - NODE_ENV=production
      - HOST=strapi.steffbeckers.eu
    networks:
      - reverse-proxy_default
      - default
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GBt4teCCcZ5QYYkScfMn
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - /root/strapi/mongodb:/data/db
      - /root/strapi/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  reverse-proxy_default:
    external: true
  default:
    internal: true
